const SERVICE_TRANSACTION_TYPES = {
  BONUS: 'BONUS',
  RACE_PRIZE: 'RACE_PRIZE',
  CASHBACK: 'CASHBACK',
  LOYALTY_REWARD: 'LOYALTY_REWARD',
  REFERRAL_REWARD: 'REFERRAL_REWARD',
  VIP_WELCOME_BONUS: 'VIP_WELCOME_BONUS',
}

const SERVICE_TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
}

export { SERVICE_TRANSACTION_STATUS, SERVICE_TRANSACTION_TYPES }
